// This file is autogenerated from 'resources/mmb4l_codepages.csv'

#if !defined(MMB4L_CODEPAGE_H)
#define MMB4L_CODEPAGE_H

#include "options.h"

typedef enum {
    kCodepageNone,
    kCodepageCMM2,
    kCodepageCP437,
    kCodepageCP1252,
    kCodepageMMB4L } CodepageEnum;

extern const NameOrdinalPair codepage_name_to_ordinal_map[];

// Note that codepage data is (const char *) so we can reuse NameOrdinalPair.
extern const NameOrdinalPair codepage_data_to_ordinal_map[];

#endif
