// This file substantially generated by Claude Sonnet 4 AI

#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>
#include <unordered_set>

extern "C" {

#include "../file.h"
#include "../mmresult.h"

// mmgetchar.c
int MMgetchar(void) {
    return 0;
}

} // extern "C"

class FileTest : public ::testing::Test {
protected:
    void SetUp() override {
        // Create a temporary test directory structure
        test_dir = std::filesystem::temp_directory_path() / "file_test";

        // Clean up any existing test directory
        if (std::filesystem::exists(test_dir)) {
            std::filesystem::remove_all(test_dir);
        }

        // Create test directory structure
        std::filesystem::create_directories(test_dir);
        std::filesystem::create_directories(test_dir / "subdir");

        // Create test files
        std::ofstream(test_dir / "file1.txt") << "test content";
        std::ofstream(test_dir / "file2.txt") << "test content";

        // Create a symbolic link (if supported)
        try {
            std::filesystem::create_symlink("file1.txt", test_dir / "link_to_file1");
        } catch (const std::exception&) {
            // Symlinks might not be supported on all systems
        }
    }

    void TearDown() override {
        // Clean up test directory
        if (std::filesystem::exists(test_dir)) {
            std::filesystem::remove_all(test_dir);
        }
    }

    std::filesystem::path test_dir;
};

// Unit tests for file_opendir(), file_readdir(), file_closedir()
class DirectoryApiTest : public FileTest {
protected:
    void SetUp() override {
        FileTest::SetUp(); // Call parent setup
    }
};

// Test successful directory opening
TEST_F(DirectoryApiTest, OpenDirSuccess) {
    DirStream *stream = nullptr;

    MmResult result = file_opendir(test_dir.c_str(), &stream);

    EXPECT_EQ(result, kOk);
    EXPECT_NE(stream, nullptr);

    if (stream) {
        file_closedir(stream);
    }
}

// Test opening non-existent directory
TEST_F(DirectoryApiTest, OpenDirNotFound) {
    DirStream *stream = nullptr;
    std::string nonexistent = test_dir / "nonexistent";

    MmResult result = file_opendir(nonexistent.c_str(), &stream);

    EXPECT_EQ(result, kFileNotFound);
    EXPECT_EQ(stream, nullptr);
}

// Test opening with null dirname
TEST_F(DirectoryApiTest, OpenDirNullPath) {
    DirStream *stream = nullptr;

    MmResult result = file_opendir(nullptr, &stream);

    EXPECT_EQ(kInternalFault, result);
    EXPECT_STREQ("dirname == NULL", mmresult_to_string(result));
    EXPECT_EQ(stream, nullptr);
}

// Test reading directory entries
TEST_F(DirectoryApiTest, ReadDirEntries) {
    DirStream *stream = nullptr;
    ASSERT_EQ(file_opendir(test_dir.c_str(), &stream), kOk);
    ASSERT_NE(stream, nullptr);

    std::vector<std::string> found_entries;
    std::vector<FileType> found_types;

    DirEntry *entry;
    MmResult result;
    while ((result = file_readdir(stream, &entry)) == kOk && entry != nullptr) {
        found_entries.push_back(entry->name);
        found_types.push_back(entry->type);
    }

    EXPECT_EQ(result, kOk); // Should end with kOk when reaching EOF

    // Verify we found expected entries (. and .. are typically included)
    EXPECT_THAT(found_entries, ::testing::Contains("."));
    EXPECT_THAT(found_entries, ::testing::Contains(".."));
    EXPECT_THAT(found_entries, ::testing::Contains("file1.txt"));
    EXPECT_THAT(found_entries, ::testing::Contains("file2.txt"));
    EXPECT_THAT(found_entries, ::testing::Contains("subdir"));

    // Check that we have reasonable entry types
    EXPECT_THAT(found_types, ::testing::Contains(kFileTypeDirectory));
    EXPECT_THAT(found_types, ::testing::Contains(kFileTypeRegularFile));

    file_closedir(stream);
}

// Test reading from null stream
TEST_F(DirectoryApiTest, ReadDirNullStream) {
    DirEntry *entry = nullptr;

    MmResult result = file_readdir(nullptr, &entry);

    EXPECT_EQ(kInternalFault, result);
    EXPECT_STREQ("stream == NULL", mmresult_to_string(result));
    EXPECT_EQ(entry, nullptr);
}

// Test multiple concurrent directory streams
TEST_F(DirectoryApiTest, MultipleConcurrentStreams) {
    // Create a second test directory
    auto test_dir2 = std::filesystem::temp_directory_path() / "dir_api_test2";
    std::filesystem::create_directories(test_dir2);
    std::ofstream(test_dir2 / "other_file.txt") << "content";

    DirStream *stream1 = nullptr;
    DirStream *stream2 = nullptr;

    // Open both directories
    ASSERT_EQ(file_opendir(test_dir.c_str(), &stream1), kOk);
    ASSERT_EQ(file_opendir(test_dir2.c_str(), &stream2), kOk);
    ASSERT_NE(stream1, nullptr);
    ASSERT_NE(stream2, nullptr);
    ASSERT_NE(stream1, stream2); // Should be different objects

    // Read from both streams alternately
    DirEntry *entry1, *entry2;
    std::vector<std::string> entries1, entries2;

    // Read first entry from each
    if (file_readdir(stream1, &entry1) == kOk && entry1) {
        entries1.push_back(entry1->name);
    }
    if (file_readdir(stream2, &entry2) == kOk && entry2) {
        entries2.push_back(entry2->name);
    }

    // The streams should be independent
    EXPECT_NE(entries1.empty() || entries2.empty(), true);

    file_closedir(stream1);
    file_closedir(stream2);

    // Cleanup
    std::filesystem::remove_all(test_dir2);
}

// Test entry type detection
TEST_F(DirectoryApiTest, EntryTypeDetection) {
    DirStream *stream = nullptr;
    ASSERT_EQ(file_opendir(test_dir.c_str(), &stream), kOk);

    std::unordered_map<std::string, FileType> entry_types;

    DirEntry *entry;
    while (file_readdir(stream, &entry) == kOk && entry != nullptr) {
        entry_types[entry->name] = entry->type;
    }

    // Check specific entry types
    if (entry_types.count("file1.txt")) {
        EXPECT_EQ(entry_types["file1.txt"], kFileTypeRegularFile);
    }
    if (entry_types.count("subdir")) {
        EXPECT_EQ(entry_types["subdir"], kFileTypeDirectory);
    }
    if (entry_types.count("link_to_file1")) {
        EXPECT_EQ(entry_types["link_to_file1"], kFileTypeSymbolicLink);
    }

    file_closedir(stream);
}

// Test very long filename handling
TEST_F(DirectoryApiTest, LongFilenames) {
    // Create a file with a name close to STRINGSIZE limit
    std::string long_name(STRINGSIZE - 10, 'x'); // Leave some margin
    long_name += ".txt";

    std::ofstream(test_dir / long_name) << "content";

    DirStream *stream = nullptr;
    ASSERT_EQ(file_opendir(test_dir.c_str(), &stream), kOk);

    bool found_long_name = false;
    DirEntry *entry;
    MmResult result;

    while ((result = file_readdir(stream, &entry)) == kOk && entry != nullptr) {
        if (entry->name == long_name) {
            found_long_name = true;
            break;
        }
    }

    EXPECT_TRUE(found_long_name);
    EXPECT_EQ(result, kOk);

    file_closedir(stream);
}

// Performance/stress test
TEST_F(DirectoryApiTest, StressTestManyFiles) {
    // Create many files for stress testing
    const int num_files = 100;
    auto stress_dir = std::filesystem::temp_directory_path() / "stress_test";
    std::filesystem::create_directories(stress_dir);

    // Create many files
    for (int i = 0; i < num_files; ++i) {
        std::string filename = "file_" + std::to_string(i) + ".txt";
        std::ofstream(stress_dir / filename) << "content " << i;
    }

    DirStream *stream = nullptr;
    ASSERT_EQ(file_opendir(stress_dir.c_str(), &stream), kOk);

    int count = 0;
    DirEntry *entry;
    while (file_readdir(stream, &entry) == kOk && entry != nullptr) {
        count++;
        // Verify name is not empty and type is reasonable
        EXPECT_GT(strlen(entry->name), 0);
        EXPECT_NE(entry->type, kFileTypeUnknown);
    }

    // Should have found at least the files we created plus . and ..
    EXPECT_GE(count, num_files + 2);

    file_closedir(stream);
    std::filesystem::remove_all(stress_dir);
}

// Test edge case: empty directory
TEST_F(DirectoryApiTest, EmptyDirectory) {
    auto empty_dir = std::filesystem::temp_directory_path() / "empty_test";
    std::filesystem::create_directories(empty_dir);

    DirStream *stream = nullptr;
    ASSERT_EQ(file_opendir(empty_dir.c_str(), &stream), kOk);

    std::vector<std::string> entries;
    DirEntry *entry;
    while (file_readdir(stream, &entry) == kOk && entry != nullptr) {
        entries.push_back(entry->name);
    }

    // Should still have . and .. entries
    EXPECT_THAT(entries, ::testing::Contains("."));
    EXPECT_THAT(entries, ::testing::Contains(".."));
    EXPECT_EQ(entries.size(), 2); // Only . and ..

    file_closedir(stream);
    std::filesystem::remove_all(empty_dir);
}

// Test proper resource cleanup
TEST_F(DirectoryApiTest, ResourceCleanup) {
    DirStream *stream = nullptr;
    ASSERT_EQ(file_opendir(test_dir.c_str(), &stream), kOk);
    ASSERT_NE(stream, nullptr);

    // Close the directory
    MmResult result = file_closedir(stream);
    EXPECT_EQ(result, kOk);

    // After closing, the memory should be freed
    // We can't directly test this without memory debugging tools,
    // but we can ensure the function returns success
}

// Test closing null stream
TEST_F(DirectoryApiTest, CloseNullStream) {
    MmResult result = file_closedir(nullptr);

    EXPECT_EQ(kInternalFault, result);
    EXPECT_STREQ("stream == NULL", mmresult_to_string(result));
}
