// This file substantially generated by Claude Sonnet 4 AI

#include <gtest/gtest.h>
#include <cstring>
#include <string>
#include <algorithm>

#include "../safe_buffer.h"

const size_t BUFFER_SIZE = 20;

class SafeBufferTest : public ::testing::Test {
protected:
    void SetUp() override {
        memset(buffer, 0, sizeof(buffer));
    }

    char buffer[BUFFER_SIZE];
    SafeBuffer sb;
};

// Test initialization
TEST_F(SafeBufferTest, InitializationTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    EXPECT_EQ(sb.base, buffer);
    EXPECT_EQ(sb.end, buffer);
    EXPECT_EQ(sb.limit, buffer + BUFFER_SIZE);
    EXPECT_EQ(sb.pos, buffer);
    EXPECT_FALSE(sb.overrun);
}

// Test reset functionality
TEST_F(SafeBufferTest, ResetTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Write some data
    safe_buffer_write(&sb, "test", 4);
    // Reset should restore initial state
    safe_buffer_reset(&sb);
    EXPECT_EQ(sb.pos, sb.base);
    EXPECT_FALSE(sb.overrun);
}

// Test write functionality
TEST_F(SafeBufferTest, WriteTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    const char *test_data = "Hello World";
    size_t test_len = strlen(test_data);
    size_t written = safe_buffer_write(&sb, test_data, test_len);
    EXPECT_EQ(written, test_len);
    EXPECT_EQ(sb.pos, sb.base + test_len);
    EXPECT_EQ(0, memcmp(buffer, test_data, test_len));
    EXPECT_FALSE(sb.overrun);
}

// Test write with overflow
TEST_F(SafeBufferTest, WriteOverflowTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    const char *long_data =
            "This is a very long string that exceeds buffer capacity";
    size_t long_len = strlen(long_data);
    size_t written = safe_buffer_write(&sb, long_data, long_len);
    EXPECT_EQ(written, BUFFER_SIZE);
    EXPECT_TRUE(sb.overrun);
    EXPECT_EQ(0, memcmp(buffer, long_data, BUFFER_SIZE));
}

// Test `write()` with overrun flag already set
TEST_F(SafeBufferTest, WriteWithOverrunTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Set overrun flag
    sb.overrun = true;
    const char *test_data = "test";
    size_t written = safe_buffer_write(&sb, test_data, 4);
    EXPECT_EQ(written, 0);
    EXPECT_TRUE(sb.overrun);
}

// Test write function with objects
TEST_F(SafeBufferTest, WriteObjectsTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    int test_ints[] = {1, 2, 3, 4};
    size_t num_ints = 4;
    size_t written = safe_buffer_write_objects(&sb, test_ints, sizeof(int),
                                               num_ints);
    EXPECT_EQ(written, num_ints);
    EXPECT_EQ(sb.pos, sb.base + sizeof(int) * num_ints);
    EXPECT_EQ(0, memcmp(buffer, test_ints, sizeof(int) * num_ints));
    EXPECT_FALSE(sb.overrun);
}

// Test write function with partial object overflow
TEST_F(SafeBufferTest, WriteObjectsPartialOverflowTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Try to write objects that would partially overflow
    int test_ints[] = {1, 2, 3, 4, 5, 6, 7, 8};
    size_t num_ints = 8;
    size_t written = safe_buffer_write_objects(&sb, test_ints, sizeof(int),
                                               num_ints);
    // Should write fewer complete objects
    EXPECT_LT(written, num_ints);
    EXPECT_TRUE(sb.overrun);
}

// Test read functionality
TEST_F(SafeBufferTest, ReadTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // First write some data
    const char *test_data = "Hello World";
    size_t test_len = strlen(test_data);
    safe_buffer_write(&sb, test_data, test_len);
    // Reset position to beginning for reading
    safe_buffer_reset(&sb);
    // Read the data back
    char read_buffer[BUFFER_SIZE];
    size_t read_count = safe_buffer_read(&sb, read_buffer, test_len);
    EXPECT_EQ(read_count, test_len);
    EXPECT_EQ(0, memcmp(read_buffer, test_data, test_len));
    EXPECT_EQ(sb.pos, sb.base + test_len);
    EXPECT_FALSE(sb.overrun);
}

// Test read with overflow
TEST_F(SafeBufferTest, ReadOverflowTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Write some data
    const char *test_data = "Hello";
    safe_buffer_write(&sb, test_data, 5);
    // Reset position to beginning for reading
    safe_buffer_reset(&sb);
    // Try to read more than available
    char read_buffer[BUFFER_SIZE];
    size_t read_count = safe_buffer_read(&sb, read_buffer, 10);
    EXPECT_EQ(read_count, 5);  // Should only read what's available
    EXPECT_TRUE(sb.overrun);
}

// Test read with overrun flag already set
TEST_F(SafeBufferTest, ReadWithOverrunTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Set overrun flag
    sb.overrun = true;
    char read_buffer[10];
    size_t read_count = safe_buffer_read(&sb, read_buffer, 5);
    EXPECT_EQ(read_count, 0);
    EXPECT_TRUE(sb.overrun);
}

// Test read function with objects
TEST_F(SafeBufferTest, ReadObjectsTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Write some integers
    int test_ints[] = {1, 2, 3, 4};
    size_t num_ints = 4;
    safe_buffer_write_objects(&sb, test_ints, sizeof(int), num_ints);
    // Reset position to beginning for reading
    safe_buffer_reset(&sb);
    // Read the integers back
    int read_ints[4];
    size_t read_count = safe_buffer_read_objects(&sb, read_ints, sizeof(int),
                                                 num_ints);
    EXPECT_EQ(read_count, num_ints);
    EXPECT_EQ(0, memcmp(read_ints, test_ints, sizeof(int) * num_ints));
    EXPECT_FALSE(sb.overrun);
}

// Test single character append (now using write internally)
TEST_F(SafeBufferTest, AppendSingleCharTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    EXPECT_EQ(0, safe_buffer_append(&sb, 'A'));
    EXPECT_EQ(sb.pos, sb.base + 1);
    EXPECT_EQ(buffer[0], 'A');
    EXPECT_FALSE(sb.overrun);
}

// Test append_bytes (now using `write()` internally)
TEST_F(SafeBufferTest, AppendBytesTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    const char *test_data = "Hello";
    size_t test_len = strlen(test_data);
    EXPECT_EQ(0, safe_buffer_append_bytes(&sb, test_data, test_len));
    EXPECT_EQ(sb.pos, sb.base + test_len);
    EXPECT_EQ(0, memcmp(buffer, test_data, test_len));
    EXPECT_FALSE(sb.overrun);
}

// Test append_string (now using `write()` internally)
TEST_F(SafeBufferTest, AppendStringTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    const char *test_str = "Hello";
    EXPECT_EQ(0, safe_buffer_append_string(&sb, test_str));
    EXPECT_EQ(sb.pos, sb.base + strlen(test_str) + 1); // +1 for null terminator
    EXPECT_STREQ(buffer, test_str);
    EXPECT_FALSE(sb.overrun);
}

// Test append functions with overflow
TEST_F(SafeBufferTest, AppendOverflowTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Fill buffer to capacity
    for (size_t i = 0; i < BUFFER_SIZE; ++i) {
        EXPECT_EQ(0, safe_buffer_append(&sb, 'A'));
    }
    // Next append should fail and set overrun
    EXPECT_EQ(-1, safe_buffer_append(&sb, 'X'));
    EXPECT_TRUE(sb.overrun);
}

// Test is_full functionality
TEST_F(SafeBufferTest, IsFullTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    EXPECT_FALSE(safe_buffer_is_full(&sb));
    // Fill buffer
    for (size_t i = 0; i < BUFFER_SIZE; ++i) {
        safe_buffer_append(&sb, 'A');
    }
    EXPECT_TRUE(safe_buffer_is_full(&sb));
}

// Test position increment
TEST_F(SafeBufferTest, IncPosTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Positive increment
    EXPECT_EQ(0, safe_buffer_inc_pos(&sb, 3));
    EXPECT_EQ(sb.pos, sb.base + 3);
    // Negative increment
    EXPECT_EQ(0, safe_buffer_inc_pos(&sb, -2));
    EXPECT_EQ(sb.pos, sb.base + 1);
    // Invalid increment (would go below base)
    EXPECT_EQ(-1, safe_buffer_inc_pos(&sb, -5));
    // Invalid increment (would go above limit)
    EXPECT_EQ(-1, safe_buffer_inc_pos(&sb, BUFFER_SIZE + 5));
}

// Test set position
TEST_F(SafeBufferTest, SetPosTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Valid position within bounds
    char *new_pos = sb.base + 5;
    EXPECT_EQ(0, safe_buffer_set_pos(&sb, new_pos));
    EXPECT_EQ(sb.pos, new_pos);
    // Invalid position below base
    EXPECT_EQ(-1, safe_buffer_set_pos(&sb, sb.base - 1));
    // Invalid position above limit
    EXPECT_EQ(-1, safe_buffer_set_pos(&sb, sb.limit + 1));
}

// Test edge case: single byte buffer
TEST_F(SafeBufferTest, SingleByteBufferTest) {
    char single_buffer[1];
    SafeBuffer single_sb;

    safe_buffer_init(&single_sb, single_buffer, 1);

    // Should be able to write one byte
    EXPECT_EQ(1, safe_buffer_write(&single_sb, "X", 1));
    EXPECT_EQ('X', single_buffer[0]);

    // Second write should fail
    EXPECT_EQ(0, safe_buffer_write(&single_sb, "Y", 1));
    EXPECT_TRUE(single_sb.overrun);
}

// Test edge case: zero-sized buffer
TEST_F(SafeBufferTest, ZeroSizeBufferTest) {
    char *null_buffer = nullptr;
    SafeBuffer zero_sb;

    safe_buffer_init(&zero_sb, null_buffer, 0);

    // Any write should fail immediately
    EXPECT_EQ(0, safe_buffer_write(&zero_sb, "X", 1));
    EXPECT_TRUE(zero_sb.overrun);
}

// Test mixed read/write operations
TEST_F(SafeBufferTest, MixedReadWriteTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Write some data
    const char *data1 = "Hello";
    safe_buffer_write(&sb, data1, 5);
    // Set position back to read
    safe_buffer_set_pos(&sb, sb.base + 2);
    // Read from middle
    char read_buf[10];
    size_t read_count = safe_buffer_read(&sb, read_buf, 3);
    EXPECT_EQ(read_count, 3);
    EXPECT_EQ(0, memcmp(read_buf, "llo", 3));
    // Continue writing from current position
    safe_buffer_write(&sb, " World", 6);
    // Verify final buffer state
    EXPECT_EQ(0, memcmp(buffer, "Hello World", 8));
}

// Test state consistency after overrun
TEST_F(SafeBufferTest, StateConsistencyAfterOverrunTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Cause overrun
    const char *long_data =
            "This is definitely too long for a 20-byte buffer and should cause overrun";
    safe_buffer_write(&sb, long_data, strlen(long_data));
    EXPECT_TRUE(sb.overrun);
    // Read/write operations should fail consistently after overrun
    EXPECT_EQ(-1, safe_buffer_append(&sb, 'X'));
    EXPECT_EQ(0, safe_buffer_write(&sb, "test", 4));
    EXPECT_EQ(0, safe_buffer_read(&sb, buffer, 4));
    // Position manipulation functions should succeed AND clear overrun flag
    EXPECT_EQ(0, safe_buffer_inc_pos(&sb, -20));
    EXPECT_FALSE(sb.overrun);  // overrun flag should be cleared
    // After position manipulation, operations should work again
    EXPECT_EQ(0, safe_buffer_append(&sb, 'X'));
    // Test the other position function
    safe_buffer_write(&sb, long_data, strlen(long_data));  // Cause overrun again
    EXPECT_TRUE(sb.overrun);
    EXPECT_EQ(0, safe_buffer_set_pos(&sb, sb.base + 1));
    EXPECT_FALSE(sb.overrun);  // overrun flag should be cleared
    // After set_pos, operations should work again
    EXPECT_EQ(0, safe_buffer_append(&sb, 'Y'));
    // Reset should still restore functionality
    safe_buffer_reset(&sb);
    EXPECT_FALSE(sb.overrun);
    EXPECT_EQ(0, safe_buffer_append(&sb, 'A'));
}

// Test boundary conditions for read/write
TEST_F(SafeBufferTest, ReadWriteBoundaryTest) {
    safe_buffer_init(&sb, buffer, BUFFER_SIZE);
    // Write exactly to capacity
    char fill_data[BUFFER_SIZE];
    for (size_t i = 0; i < BUFFER_SIZE; ++i) {
        fill_data[i] = 'A' + (i % 26);
    }
    size_t written = safe_buffer_write(&sb, fill_data, BUFFER_SIZE);
    EXPECT_EQ(written, BUFFER_SIZE);
    EXPECT_FALSE(sb.overrun);
    EXPECT_TRUE(safe_buffer_is_full(&sb));
    // One more write should trigger overrun
    written = safe_buffer_write(&sb, "X", 1);
    EXPECT_EQ(written, 0);
    EXPECT_TRUE(sb.overrun);
}
